version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Cấu hình nginx
      - ./cert.pem:/etc/nginx/cert.pem:ro  # Chứng chỉ SSL
      - ./privkey.pem:/etc/nginx/privkey.pem:ro  # Khóa riêng SSL
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front-end
      - admin-client
    networks:
      - dev

  back-end:
    image: quangnv1911/bearpo-back-end:v1
    environment:
      - PORT=3008
      - MONGO_DB_URL=mongodb+srv://quangnv1911:yGLniiAAhh7a93u5@wukongfood.oshcg.mongodb.net/?retryWrites=true&w=majority&appName=WukongFood
      - PRIVATE_KEY=p5XcBBTii7a+6p90blNrQ5qKZWYc9AN3ZsPxokEndvqxqHI71aaZ/Yrz51pNMjgy2nsxlGWqMM7KLJ5dV8lQvyQCMG057xUWW0KPwnwbU0o6+l3w5PdQe50jvcYWWwbKExJgUAb>      
      - BACK_END_HOST=https://api.wukongfood.site
      - CLOUD_NAME=dt4zxti7x
      - API_KEY=145527241165396
      - API_SECRET=TjbiU9lmYCgdIPAod6hiG4XHf3I
      - TELEGRAMBOT_TOKEN=6935212540:AAG68j80HgH1DcXw4emEqf_1D_w4XYxsimI
      - TELEGRAM_GROUPID=-4509219046
    networks:
      - dev
    ports:
      - "3008:3008"

  front-end:
    image: quangnv1911/bearpo-front-end:v1
    networks:
      - dev

  admin-client:
    image: quangnv1911/bearpo-admin-client:v1
    networks:
      - dev
    ports:
      - "3000:80"
  json-server:
    image: quangnv1911/bearpo-json-server:v1
    ports:
      - "3001:3000"

networks:
  dev:
